services:
  delivery-api:
    build: .
    container_name: delivery-api
    restart: always
    networks:
      - root_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.delivery-api.rule=Host(`reparto.bluegreenpl.com`)"
      - "traefik.http.routers.delivery-api.tls=true"
      - "traefik.http.routers.delivery-api.entrypoints=websecure"
      - "traefik.http.routers.delivery-api.tls.certresolver=mytlschallenge"
      - "traefik.http.services.delivery-api.loadbalancer.server.port=8000"
      # Middleware CORS
      - "traefik.http.middlewares.delivery-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS,PATCH"
      - "traefik.http.middlewares.delivery-cors.headers.accesscontrolalloworiginlistregex=https://.*\\.pages\\.dev,https://reparto\\.bluegreenpl\\.com"
      - "traefik.http.middlewares.delivery-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.delivery-cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.delivery-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.delivery-cors.headers.addvaryheader=true"
      - "traefik.http.routers.delivery-api.middlewares=delivery-cors"
    volumes:
      - ./data:/app/data

networks:
  root_default:
    external: true
